server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password1234
    url: jdbc:mysql://localhost:3306/springsecuritydemo
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true


#server:
#  servlet:
#    context-path: /springsecurity